// Turns the PGN lines below into site/games.js. chess.js checks every move, so the wall only ever plays legal chess.
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Chess } from "chess.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

// The hero game: you have White and win with a smothered mate.
const HERO = "1.e4 c6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Nd7 5.Qe2 Ngf6 6.Nd6#";

// Well-known miniatures and opening lines. Lines without mate end in a resignation.
const WALL = [
  "1.e4 e5 2.Nf3 d6 3.Bc4 Bg4 4.Nc3 g6 5.Nxe5 Bxd1 6.Bxf7+ Ke7 7.Nd5#",
  "1.e4 e5 2.Nf3 d6 3.d4 Bg4 4.dxe5 Bxf3 5.Qxf3 dxe5 6.Bc4 Nf6 7.Qb3 Qe7 8.Nc3 c6 9.Bg5 b5 10.Nxb5 cxb5 11.Bxb5+ Nbd7 12.O-O-O Rd8 13.Rxd7 Rxd7 14.Rd1 Qe6 15.Bxd7+ Nxd7 16.Qb8+ Nxb8 17.Rd8#",
  "1.e4 e5 2.Nf3 Nc6 3.Bc4 Nd4 4.Nxe5 Qg5 5.Nxf7 Qxg2 6.Rf1 Qxe4+ 7.Be2 Nf3#",
  "1.d4 e5 2.dxe5 Nc6 3.Nf3 Qe7 4.Bf4 Qb4+ 5.Bd2 Qxb2 6.Bc3 Bb4 7.Qd2 Bxc3 8.Qxc3 Qc1#",
  "1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 4.c3 Nf6 5.d4 exd4 6.cxd4 Bb4+ 7.Bd2 Bxd2+ 8.Nbxd2 d5 9.exd5 Nxd5 10.Qb3 Nce7 11.O-O O-O 12.Rfe1 c6",
  "1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6 6.Be3 e5 7.Nb3 Be6 8.f3 Be7 9.Qd2 O-O 10.O-O-O Nbd7 11.g4 b5 12.g5 b4",
  "1.d4 d5 2.c4 e6 3.Nc3 Nf6 4.Bg5 Be7 5.e3 O-O 6.Nf3 h6 7.Bh4 b6 8.cxd5 Nxd5 9.Bxe7 Qxe7 10.Nxd5 exd5 11.Rc1 Be6",
  "1.d4 d5 2.Bf4 Nf6 3.e3 c5 4.c3 Nc6 5.Nd2 e6 6.Ngf3 Bd6 7.Bg3 O-O 8.Bd3 b6 9.Ne5 Bb7 10.f4 Ne7",
  "1.e4 c6 2.d4 d5 3.e5 Bf5 4.Nf3 e6 5.Be2 c5 6.Be3 cxd4 7.Nxd4 Ne7 8.c4 Nbc6 9.Qa4 dxc4",
  "1.e4 e5 2.Nf3 Nc6 3.Bb5 a6 4.Ba4 Nf6 5.O-O Be7 6.Re1 b5 7.Bb3 d6 8.c3 O-O 9.h3 Na5 10.Bc2 c5 11.d4 Qc7",
  "1.e4 c6 2.d4 d5 3.Nc3 dxe4 4.Nxe4 Nd7 5.Qe2 Ngf6 6.Nd6#",
  "1.e4 e5 2.Qh5 Nc6 3.Bc4 Nf6 4.Qxf7#",
  "1.d4 Nf6 2.c4 g6 3.Nc3 Bg7 4.e4 d6 5.Nf3 O-O 6.Be2 e5 7.O-O Nc6 8.d5 Ne7 9.Ne1 Nd7 10.Nd3 f5",
  "1.e4 e6 2.d4 d5 3.Nc3 Bb4 4.e5 c5 5.a3 Bxc3+ 6.bxc3 Ne7 7.Qg4 O-O 8.Bd3 Nbc6 9.Qh5 Ng6",
  "1.c4 e5 2.Nc3 Nf6 3.Nf3 Nc6 4.g3 d5 5.cxd5 Nxd5 6.Bg2 Nb6 7.O-O Be7 8.d3 O-O 9.Be3 Be6",
  "1.f3 e5 2.g4 Qh4#",
];

function convert(pgn) {
  const chess = new Chess();
  chess.loadPgn(pgn);
  const moves = chess.history({ verbose: true }).map((m) => {
    const out = [m.from, m.to];
    if (m.flags.includes("k")) out.push("k");
    else if (m.flags.includes("q")) out.push("q");
    else if (m.flags.includes("e")) out.push("e");
    if (m.promotion) out.push("=" + m.promotion);
    return out.join(" ");
  });
  const mate = chess.isCheckmate();
  const winner = mate ? (chess.turn() === "w" ? "b" : "w") : chess.turn() === "w" ? "b" : "w";
  return { m: moves.join(","), end: mate ? "mate" : "resign", w: winner };
}

const hero = convert(HERO);
if (hero.end !== "mate" || hero.w !== "w") throw new Error("Hero game must end in mate for White");
const wall = WALL.map(convert);

const out = `// Generated by scripts/games.mjs from PGN checked with chess.js. Do not edit by hand.
export const HERO_GAME = ${JSON.stringify(hero)};
export const WALL_GAMES = ${JSON.stringify(wall)};
`;
await writeFile(path.join(root, "site", "games.js"), out);
console.log(`games.js: hero ${hero.m.split(",").length} plies, ${wall.length} wall games, ${wall.filter((g) => g.end === "mate").length} end in mate`);
